version: '3.8'

services:
  app:
    image: jakegirard/drawerganizer:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
    driver: local